### ISSUE TITLE
Missing file jsconfig.json in template js-tailwindcss 

### ISSUE THREAD

**Issue by timdimas** [solidjs/templates#92]
I noticed that this file is missing jsconfig.json
``` yaml
{
  "compilerOptions": {
    "strict": true,
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "jsx": "preserve",
    "jsxImportSource": "solid-js",
    "types": ["vite/client"],
    "noEmit": true,
    "isolatedModules": true
  }
} 
```
